#!/usr/bin/env python3
"""export_ides.py — generate multi-assistant exports of the plugin SKILLs.

Renders the same domain knowledge held in ``plugins/<domain>/skills/<skill>/SKILL.md``
into assistant-native instruction files under ``ides/`` for GitHub Copilot, Gemini,
OpenCode, and Codex. The ``plugins/`` tree remains the single source of truth — the
``ides/`` files are generated mirrors (an index + per-domain summary that points back
to the canonical SKILL), kept concise to avoid drift.

Run from the repo root:

    python3 tools/export_ides.py            # regenerate ides/ from plugins/
    python3 tools/export_ides.py --check    # fail if ides/ is stale (CI-friendly)

Pure standard library — the SKILL frontmatter is parsed with a small reader so no
YAML dependency is needed.
"""

from __future__ import annotations

import argparse
import glob
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# target -> (output path relative to ides/, assistant display name)
TARGETS = {
    "copilot": (".github/copilot-instructions.md", "GitHub Copilot"),
    "gemini": ("GEMINI.md", "Gemini"),
    "opencode": ("AGENTS.md", "OpenCode"),
    "codex": ("AGENTS.md", "Codex"),
}

GENERATED_NOTE = (
    "> _Generated by `tools/export_ides.py` from the `plugins/` SKILLs — "
    "do not edit by hand. The canonical source is each domain's `SKILL.md`._"
)


def extract_stage_sequence(text):
    """Return the first non-empty line under a '## Stage Sequence' header, sans backticks."""
    lines = text.splitlines()
    for idx, line in enumerate(lines):
        if line.strip().startswith("## Stage Sequence"):
            for nxt in lines[idx + 1:]:
                if nxt.strip():
                    return nxt.strip().strip("`")
    return ""


def parse_skill(path):
    """Return {name, description, stage_sequence, purpose, rel} from a SKILL.md."""
    text = open(path).read()
    name = description = stage_sequence = purpose = ""

    # --- frontmatter (between the first two '---' lines) ---
    if text.startswith("---"):
        end = text.find("\n---", 3)
        fm = text[3:end] if end != -1 else ""
        body = text[end + 4:] if end != -1 else text
        lines = fm.splitlines()
        i = 0
        while i < len(lines):
            line = lines[i]
            if line.startswith("name:"):
                name = line.split(":", 1)[1].strip()
            elif line.startswith("description:"):
                val = line.split(":", 1)[1].strip()
                if val in (">", "|", ">-", "|-", ""):
                    # folded/literal block: gather following indented lines
                    parts = []
                    i += 1
                    while i < len(lines) and (lines[i].startswith((" ", "\t")) or not lines[i].strip()):
                        parts.append(lines[i].strip())
                        i += 1
                    description = " ".join(p for p in parts if p)
                    continue
                description = val
            i += 1
    else:
        body = text

    # --- body sections ---
    stage_sequence = extract_stage_sequence(body)
    body_lines = body.splitlines()
    for idx, line in enumerate(body_lines):
        if line.strip() == "## Purpose":
            para = []
            for nxt in body_lines[idx + 1:]:
                if nxt.strip().startswith("#"):
                    break
                if nxt.strip():
                    para.append(nxt.strip())
                elif para:
                    break
            purpose = " ".join(para)

    # SKILLs use per-stage '## Stage:' headers; the stage *sequence* lives in the
    # sibling orchestrator agent. Fall back to it when the SKILL has no sequence line.
    if not stage_sequence:
        plugin_dir = os.path.dirname(os.path.dirname(os.path.dirname(path)))
        for agent_path in sorted(glob.glob(os.path.join(plugin_dir, "agents", "*.md"))):
            seq = extract_stage_sequence(open(agent_path).read())
            if seq:
                stage_sequence = seq
                break

    return {
        "name": name,
        "description": description,
        "stage_sequence": stage_sequence,
        "purpose": purpose,
        "rel": os.path.relpath(path, REPO_ROOT),
    }


def collect_skills():
    paths = sorted(glob.glob(os.path.join(REPO_ROOT, "plugins/*/skills/*/SKILL.md")))
    return [parse_skill(p) for p in paths]


def render(assistant_name, skills):
    out = []
    out.append(f"# analog-chip-design-agents — {assistant_name} instructions")
    out.append("")
    out.append(GENERATED_NOTE)
    out.append("")
    out.append(
        "This project is an analog / mixed-signal + RF chip-design assistant. Each domain "
        "below owns a stage of the spec→schematic→SPICE→layout→sign-off→RF/EM→top-integration "
        "flow, with explicit QoR gates and loop-back rules. When a task matches a domain, read "
        "that domain's canonical `SKILL.md` (linked) and follow its stage sequence, QoR metrics, "
        "and output requirements. Cross-domain feedback runs through `design_state.json` "
        "(see `docs/design_state_schema.md`)."
    )
    out.append("")
    out.append("## Domains")
    out.append("")
    out.append("| Domain | Stage sequence | Canonical SKILL |")
    out.append("|--------|----------------|-----------------|")
    for s in skills:
        stages = s["stage_sequence"] or "—"
        out.append(f"| `{s['name']}` | {stages} | [`{s['rel']}`]({os.path.join('..', '..', s['rel'])}) |")
    out.append("")
    out.append("## Domain detail")
    out.append("")
    for s in skills:
        out.append(f"### {s['name']}")
        out.append("")
        if s["description"]:
            out.append(s["description"])
            out.append("")
        if s["stage_sequence"]:
            out.append(f"**Stages:** `{s['stage_sequence']}`")
            out.append("")
        out.append(f"Canonical knowledge: [`{s['rel']}`]({os.path.join('..', '..', s['rel'])})")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_index():
    out = [
        "# ides/ — multi-assistant exports",
        "",
        GENERATED_NOTE,
        "",
        "These directories mirror the `plugins/` SKILLs into formats other AI coding "
        "assistants read, so the same analog/mixed-signal + RF domain knowledge is available "
        "outside Claude Code. The **source of truth is `plugins/<domain>/skills/<skill>/SKILL.md`**; "
        "regenerate after changing a SKILL with:",
        "",
        "```bash",
        "python3 tools/export_ides.py",
        "```",
        "",
        "| Assistant | File |",
        "|-----------|------|",
    ]
    for key, (relpath, display) in TARGETS.items():
        out.append(f"| {display} | [`{key}/{relpath}`]({key}/{relpath}) |")
    out.append("")
    return "\n".join(out) + "\n"


def write_if_changed(path, content, check):
    existing = open(path).read() if os.path.isfile(path) else None
    if existing == content:
        return False
    if check:
        print(f"STALE: {os.path.relpath(path, REPO_ROOT)}", file=sys.stderr)
        return True
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)
    print(f"wrote {os.path.relpath(path, REPO_ROOT)}")
    return True


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="Exit non-zero if any ides/ file is out of date (do not write)")
    args = parser.parse_args(argv)

    skills = collect_skills()
    if not skills:
        print("ERROR: no SKILL.md files found under plugins/", file=sys.stderr)
        return 2

    ides_root = os.path.join(REPO_ROOT, "ides")
    stale = False
    stale |= write_if_changed(os.path.join(ides_root, "README.md"), render_index(), args.check)
    for key, (relpath, display) in TARGETS.items():
        content = render(display, skills)
        stale |= write_if_changed(os.path.join(ides_root, key, relpath), content, args.check)

    if args.check and stale:
        print("ides/ is out of date — run: python3 tools/export_ides.py", file=sys.stderr)
        return 1
    if args.check:
        print("ides/ is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
